name: Update IPTV Index

on:
  workflow_dispatch:
  push:
    paths:
      - 'streams/*.m3u'
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate index.m3u
        run: |
          echo "#EXTM3U" > index.m3u

          for file in streams/*.m3u; do

            group=$(basename "$file" .m3u)

            # Custom folder names
            if [ "$group" = "my" ]; then group="Malaysia"; fi
            if [ "$group" = "ae" ]; then group="UAE"; fi
            if [ "$group" = "zhuyutvdrama" ]; then group="逐玉"; fi

            echo "" >> index.m3u

            awk -v grp="$group" '
            /^#EXTINF/ {

                # remove old group-title if exists
                gsub(/group-title="[^"]*"/, "")

                # add new group-title
                sub(/,/, " group-title=\"" grp "\",", $0)

                print
                next
            }

            {
                print
            }
            ' "$file" | tail -n +2 >> index.m3u

          done

      - name: Commit updated index.m3u
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add index.m3u

          git diff --cached --quiet || git commit -m "Auto update index.m3u"

          git push
