name: Update IPTV Index

on:
  workflow_dispatch:
  push:
    paths:
      - 'streams/*.m3u'
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

concurrency:
  group: update-iptv-index
  cancel-in-progress: false

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate index.m3u
        run: |
          echo "#EXTM3U" > index.m3u

          for file in streams/*.m3u; do

            group=$(basename "$file" .m3u)

            # Custom folder names
            if [ "$group" = "my" ]; then group="Malaysia"; fi
            if [ "$group" = "ae" ]; then group="UAE"; fi
            if [ "$group" = "zhuyutvdrama" ]; then group="逐玉"; fi

            echo "" >> index.m3u

            awk -v grp="$group" '
            /^#EXTINF/ {

                # remove old group-title if exists
                gsub(/group-title="[^"]*"/, "")

                # add new group-title
                sub(/,/, " group-title=\"" grp "\",", $0)

                print
                next
            }

            {
                print
            }
            ' "$file" | tail -n +2 >> index.m3u

          done

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add index.m3u

          # Exit if no changes
          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "Auto update index.m3u"

      - name: Push with retry until success
        run: |
          MAX_RETRIES=10
          RETRY=0

          until [ $RETRY -ge $MAX_RETRIES ]
          do
            echo "Attempt $((RETRY+1)) to push..."

            git pull --rebase origin main

            if git push; then
              echo "Push successful!"
              exit 0
            fi

            RETRY=$((RETRY+1))
            echo "Push failed. Retrying in 10 seconds..."
            sleep 10
          done

          echo "Failed after $MAX_RETRIES attempts."
          exit 1
